// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/*
 * Airflow API (Stable)
 *
 * Apache Airflow management API.
 *
 * API version: 1.0.0
 * Contact: dev@airflow.apache.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package airflow
import (
	"time"
)
// Task struct for Task
type Task struct {
	ClassRef ClassReference `json:"class_ref,omitempty"`
	TaskId string `json:"task_id,omitempty"`
	Owner string `json:"owner,omitempty"`
	StartDate time.Time `json:"start_date,omitempty"`
	EndDate *time.Time `json:"end_date,omitempty"`
	TriggerRule TriggerRule `json:"trigger_rule,omitempty"`
	ExtraLinks []TaskExtraLinks `json:"extra_links,omitempty"`
	DependsOnPast bool `json:"depends_on_past,omitempty"`
	WaitForDownstream bool `json:"wait_for_downstream,omitempty"`
	Retries float32 `json:"retries,omitempty"`
	Queue string `json:"queue,omitempty"`
	Pool string `json:"pool,omitempty"`
	PoolSlots float32 `json:"pool_slots,omitempty"`
	ExecutionTimeout TimeDelta `json:"execution_timeout,omitempty"`
	RetryDelay TimeDelta `json:"retry_delay,omitempty"`
	RetryExponentialBackoff bool `json:"retry_exponential_backoff,omitempty"`
	PriorityWeight float32 `json:"priority_weight,omitempty"`
	WeightRule WeightRule `json:"weight_rule,omitempty"`
	UiColor string `json:"ui_color,omitempty"`
	UiFgcolor string `json:"ui_fgcolor,omitempty"`
	TemplateFields []string `json:"template_fields,omitempty"`
	SubDag Dag `json:"sub_dag,omitempty"`
	DownstreamTaskIds []string `json:"downstream_task_ids,omitempty"`
}
