// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/*
 * Airflow API (Stable)
 *
 * Apache Airflow management API.
 *
 * API version: 1.0.0
 * Contact: dev@airflow.apache.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package airflow
// TaskInstance struct for TaskInstance
type TaskInstance struct {
	TaskId string `json:"task_id,omitempty"`
	DagId string `json:"dag_id,omitempty"`
	ExecutionDate string `json:"execution_date,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
	Duration float32 `json:"duration,omitempty"`
	State TaskState `json:"state,omitempty"`
	TryNumber int32 `json:"try_number,omitempty"`
	MaxTries int32 `json:"max_tries,omitempty"`
	Hostname string `json:"hostname,omitempty"`
	Unixname string `json:"unixname,omitempty"`
	Pool string `json:"pool,omitempty"`
	PoolSlots int32 `json:"pool_slots,omitempty"`
	Queue string `json:"queue,omitempty"`
	PriorityWeight int32 `json:"priority_weight,omitempty"`
	Operator string `json:"operator,omitempty"`
	QueuedWhen string `json:"queued_when,omitempty"`
	Pid int32 `json:"pid,omitempty"`
	ExecutorConfig string `json:"executor_config,omitempty"`
	SlaMiss SlaMiss `json:"sla_miss,omitempty"`
}
