// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/*
 * Airflow API (Stable)
 *
 * Apache Airflow management API.
 *
 * API version: 1.0.0
 * Contact: dev@airflow.apache.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package airflow
// TriggerRule the model 'TriggerRule'
type TriggerRule string

// List of TriggerRule
const (
	TRIGGERRULE_ALL_SUCCESS TriggerRule = "all_success"
	TRIGGERRULE_ALL_FAILED TriggerRule = "all_failed"
	TRIGGERRULE_ALL_DONE TriggerRule = "all_done"
	TRIGGERRULE_ONE_SUCCESS TriggerRule = "one_success"
	TRIGGERRULE_ONE_FAILED TriggerRule = "one_failed"
	TRIGGERRULE_NONE_FAILED TriggerRule = "none_failed"
	TRIGGERRULE_NONE_SKIPPED TriggerRule = "none_skipped"
	TRIGGERRULE_NONE_FAILED_OR_SKIPPED TriggerRule = "none_failed_or_skipped"
	TRIGGERRULE_DUMMY TriggerRule = "dummy"
)
